

const actionTypes = {
    LOAD_CHECKLISTS: "LOAD_CHECKLISTS",
    LOAD_CHECKLISTS_SUCCESS: "LOAD_CHECKLISTS_SUCCESS",
    LOAD_CHECKLISTS_FAIL: "LOAD_CHECKLISTS_FAIL",
    REINITIALIZE_CHECKLISTS: "REINITIALIZE_CHECKLISTS",

    LOAD_TAXONOMIES: "LOAD_TAXONOMIES",
    LOAD_TAXONOMIES_SUCCESS: "LOAD_TAXONOMIES_SUCCESS",
    LOAD_TAXONOMIES_FAIL: "LOAD_TAXONOMIES_FAIL",
    REINITIALIZE_TAXONOMIES: "REINITIALIZE_TAXONOMIES"
    
};

export default actionTypes;