import fx from "../../fx";

const actionTypes = {
    LOAD_CHECKLISTS: "LOAD_CHECKLISTS",
    LOAD_CHECKLISTS_SUCCESS: "LOAD_CHECKLISTS_SUCCESS",
    LOAD_CHECKLISTS_FAIL: "LOAD_CHECKLISTS_FAIL",
    REINITIALIZE_CHECKLISTS: "REINITIALIZE_CHECKLISTS",

    LOAD_TAXONOMIES: "LOAD_TAXONOMIES",
    LOAD_TAXONOMIES_SUCCESS: "LOAD_TAXONOMIES_SUCCESS",
    LOAD_TAXONOMIES_FAIL: "LOAD_TAXONOMIES_FAIL",
    REINITIALIZE_TAXONOMIES: "REINITIALIZE_TAXONOMIES",

    SET_USER_INFO: "SET_USER_INFO",
    CLEAR_USER_INFO: "CLEAR_USER_INFO",



    UPDATE_PROFILE: "UPDATE_PROFILE",

    STORE_INITIALIZED: "STORE_INITIALIZED",
    ...fx.actionTypes

};

export default actionTypes;